### ISSUE TITLE
Remove panel mode options: Only keep no panel mode

### ISSUE THREAD

**Issue by gnumdk** [gnumdk/eolie#151]
Hello,

just a question, I started Eolie by playing with many mode. Recently, someone ask for a "no panel" mode and I'm now using this option as default on my laptop, I love it (it needs some more tweaks to be perfect) and even if 80% of code is share between all panel modes, removing all other modes will make code a  lot cleaner.

So it's just a question, keeping all options is not too hard for now. But if you prefer other modes, please tell me why :)

**Comment by gnumdk** [comment]
@julianrichen @GabMus @bagage @M5oul @DerpyCrabs @evfool 
I ping you all as identified Eolie users :-) What is your mood about this?

**Comment by bagage** [comment]
Not tested yet the new mode, but I personally like the minimal mode because most of the time `1 tab = 1 task to do`, so seeing my opened tabs let me estimate how much time I have to spend. Will need to spend some time with the new mode to exacly know what I like in/miss from the minimal mode.

**Comment by gnumdk** [comment]
>so seeing my opened tabs let me estimate how much time I have to spend

No panel mode shows you how many pages are opened ;)

**Comment by fastrizwaan** [comment]
the website name/icon in the tabs gives better perspective of what is to be done; it is not just the number of pages open which will make it useful. 

The reason gnome users love dash-to-panel or dash-to-dock extensions because they give visual information about other applications. The default gnome dash makes it difficult to see things in parallel in the name of "focus oriented" workflow; instead this "focus on one task" makes it difficult to do multi tasking or sequential tasking; which is normally all users do.

Tabs are more important in web browsers because they make multi tasking easier and helps the user to "pre" launch websites in a sequence as a todo list; so that the user can switch to other tab/task when one task is done.

I'd suggest, give flexibility and let eolie help the users of different work flow to work naturally, instead of forcing gnome like "do things as the developers say" or make an extension to get the things behave as you want, way.

Inclusiveness is better than exclusiveness.

Thanks

**Comment by d9h02f** [comment]
I agree with @fastrizwaan. I actually like the way GNOME Shell works, but inside an application I want to see the tabs. It lets me keep track of what I'm doing, not only how many things I'm doing.

**Comment by gnumdk** [comment]
Yes, but there is epiphany for that :p

BTW, @fastrizwaan comment is useless for me, it does not find Gnome Shell workflow logical while I find taskbar/panel to be the wrong way to do.

**Comment by fastrizwaan** [comment]
@gnumdk I'm all for innovative ideas yet keeping the well established paradigm alive, more like modern+traditional ;-). 

Yes, you can really make eolie a unique browser; go ahead, remove other modes; 

no panel mode, should show pages preview on hovering the pages button or something which gives peek into other pages, this is useful when we are working with 2 or more related web pages.

If you can get the zoom in and out animation for page switching that would make it awesome; like this
https://jimmac.fedorapeople.org/gnome3/web-page-switching.webm

**Comment by gnumdk** [comment]
Finnally reword all the code mixing "No panel mode" and "Minimal panel mode". It now works like Gnome Shell, sites are grouped on the left and clicking on a site show pages.

**Comment by fastrizwaan** [comment]
actually, this new behavior is similar to "unity panel"  on 2nd click and not gnome shell. 

If we have 2 windows, gnome-shell keeps switching windows on any number of clicks, 
whereas eolie always show both the windows on 1st click
but unity panel, switches to the inactive window first then on second click presents both windows to the user for selection (much like eolie 1st click)

If you want gnome-shell like behavior, just switch grouped pages on clicks.

Making things easy for user is for extension developers (someone else), not gnome-shell.
