### ISSUE TITLE
I can not open links with mouse in a page after 

### ISSUE THREAD

**Issue by cgiannakidis70** [gnumdk/eolie#263]
### Environment
- Eolie version: 0.9.7
- GTK+ version: 3.22
- Operating system: Linux christoforos-Lenovo-G50-80 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

 I press "Leave Fullscreen " button, as in attachment.The browser freezes.
![screenshot from 2017-10-29 01-21-26](https://user-images.githubusercontent.com/33185625/32139077-ace78926-bc48-11e7-9117-bc9b7210090b.png)

**Comment by gnumdk** [comment]
Note: looks like you are using Ubuntu. If not using flatpak (I guess as it's not really supported by Ubuntu), you will experience segfaults in Eolie due to a bug in python-gobject. (fixed in 3.26.1).

Bad news, Ubuntu is shipping an obsolete version (3.24) so I guess an update to 3.26.1 will not happen. But you can try to report a bug...

**Comment by cgiannakidis70** [comment]
Hi 
I am using Ubuntu 17.10 with Gnome 3.26.1.How can I use flatpak?

**Comment by gnumdk** [comment]
I will provide Ubuntu PPA soon. But just look here for flatpak:  https://flathub.org/
You need to install flatpak cmdline

**Comment by cgiannakidis70** [comment]
Thanks for your reply.I have installed flatpak from repository.

**Comment by gnumdk** [comment]
@cgiannakidis70 In prime time:
https://launchpad.net/~gnumdk/+archive/ubuntu/eolie

PPA with Ubuntu packages. This will allow you to have Eolie running with Ubuntu theme.
You needs to remove flatpak package with:
flatpak --user uninstall org.gnome.Eolie
or
flatpak uninstall org.gnome.Eolie
